# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import commspb_pb2 as commspb__pb2


class CommsServiceStub(object):
    """option go_package = "github.com/AhmetSBulbul/go-grpc-stream/protos";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinChannel = channel.unary_stream(
                '/commspb.CommsService/JoinChannel',
                request_serializer=commspb__pb2.Channel.SerializeToString,
                response_deserializer=commspb__pb2.Message.FromString,
                )
        self.SendMessage = channel.stream_unary(
                '/commspb.CommsService/SendMessage',
                request_serializer=commspb__pb2.Message.SerializeToString,
                response_deserializer=commspb__pb2.MessageAck.FromString,
                )


class CommsServiceServicer(object):
    """option go_package = "github.com/AhmetSBulbul/go-grpc-stream/protos";

    """

    def JoinChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinChannel': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinChannel,
                    request_deserializer=commspb__pb2.Channel.FromString,
                    response_serializer=commspb__pb2.Message.SerializeToString,
            ),
            'SendMessage': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=commspb__pb2.Message.FromString,
                    response_serializer=commspb__pb2.MessageAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'commspb.CommsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommsService(object):
    """option go_package = "github.com/AhmetSBulbul/go-grpc-stream/protos";

    """

    @staticmethod
    def JoinChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/commspb.CommsService/JoinChannel',
            commspb__pb2.Channel.SerializeToString,
            commspb__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/commspb.CommsService/SendMessage',
            commspb__pb2.Message.SerializeToString,
            commspb__pb2.MessageAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
